modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/hammertater/treechop/issues"

[[mods]]
modId="treechopjadeplugin"
version="${file.jarVersion}"
displayName="HT's TreeChop Jade Plugin"
updateJSONURL="https://raw.githubusercontent.com/hammertater/treechop/main/jade-plugin-forge/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/treechop"
logoFile= "../logo.png"
credits="This one goes out to all the lumberjacks."
authors="HammerTater"
description="Adds Jade support for HT's TreeChop."

[[dependencies.treechopjadeplugin]]
modId="treechop"
mandatory=true
versionRange="[0.16.0,)"
ordering="NONE"
side="CLIENT"
